### ISSUE TITLE
pytorch2onnx conversion error

### ISSUE THREAD

**Issue by devloper13** [ovextra/mmdetection#108]
I am trying to convert a fintuned model of faster_rcnn_x101_64x4d_fpn_1x_coco.
But facing with this error :  TypeError: __init__() got an unexpected keyword argument 'output_size'

What could this error mean?

Full error:
Traceback (most recent call last):
  File "tools/export.py", line 297, in <module>
    sys.exit(main(args) or 0)
  File "/home/ubuntu/mmdetection/mmdet/apis/inference.py", line 33, in init_detector
    model = build_detector(config.model, test_cfg=config.test_cfg)
    return obj_cls(**args)
  File "/home/ubuntu/mmdetection/mmdet/models/detectors/faster_rcnn.py", line 23, in __init__
    pretrained=pretrained)
  File "/home/ubuntu/mmdetection/mmdet/models/detectors/two_stage.py", line 44, in __init__
    self.roi_head = build_head(roi_head)
  File "/home/ubuntu/mmdetection/mmdet/models/builder.py", line 40, in build_head
    return build(cfg, HEADS)
  File "/home/ubuntu/mmdetection/mmdet/models/builder.py", line 20, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/home/ubuntu/anaconda3/envs/ote-det/lib/python3.7/site-packages/mmcv/utils/registry.py", line 167, in build_from_cfg
    return obj_cls(**args)
  File "/home/ubuntu/mmdetection/mmdet/models/roi_heads/base_roi_head.py", line 26, in __init__
    self.init_bbox_head(bbox_roi_extractor, bbox_head)
  File "/home/ubuntu/mmdetection/mmdet/models/roi_heads/standard_roi_head.py", line 27, in init_bbox_head
    self.bbox_roi_extractor = build_roi_extractor(bbox_roi_extractor)
  File "/home/ubuntu/mmdetection/mmdet/models/builder.py", line 32, in build_roi_extractor
    return build(cfg, ROI_EXTRACTORS)
  File "/home/ubuntu/mmdetection/mmdet/models/builder.py", line 20, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/home/ubuntu/anaconda3/envs/ote-det/lib/python3.7/site-packages/mmcv/utils/registry.py", line 167, in build_from_cfg
    return obj_cls(**args)
  File "/home/ubuntu/mmdetection/mmdet/models/roi_heads/roi_extractors/single_level.py", line 38, in __init__
    self.roi_layers = self.build_roi_layers(roi_layer, featmap_strides)
  File "/home/ubuntu/mmdetection/mmdet/models/roi_heads/roi_extractors/single_level.py", line 58, in build_roi_layers
    [layer_cls(spatial_scale=1 / s, **cfg) for s in featmap_strides])
  File "/home/ubuntu/mmdetection/mmdet/models/roi_heads/roi_extractors/single_level.py", line 58, in <listcomp>
    [layer_cls(spatial_scale=1 / s, **cfg) for s in featmap_strides])
TypeError: __init__() got an unexpected keyword argument 'output_size'

**Comment by druzhkov-paul** [comment]
@devloper13 Please use `tools/export.py` script to convert PyTorch model to ONNX representation. This [doc page](https://github.com/openvinotoolkit/mmdetection/blob/ote/docs/getting_started.md#export-pretrained-model-to-onnx-and-openvino-ir) describes how to use it.

**Comment by devloper13** [comment]
I'm facing the same error. I have updated my issue with the full error.

**Comment by druzhkov-paul** [comment]
@devloper13 This is more informative now, thanks. It looks like the model has been trained in mmdet version which is not fully compatible with ours. I guess in this particular case replacing 'output_size' with 'out_size' in config file (something like that: `roi_layer=dict(type='RoIAlign', out_size=7, sample_num=0)`) should resolve the issue.

**Comment by devloper13** [comment]
This helped!  Another parameter iou_threshold had to be written as iou_thr. 
However I have some other questions I'll raise another issue for that! 
Thanks!
