### ISSUE TITLE
TracerWarning and UserWarning

### ISSUE THREAD

**Issue by devloper13** [ovextra/mmdetection#109]
I'm getting few TraceWarning and UserWarning like below:

```
File "/home/ubuntu/mmdetection/mmdet/models/detectors/two_stage.py", line 44, in __init__
    self.roi_head = build_head(roi_head)
    [layer_cls(spatial_scale=1 / s, **cfg) for s in featmap_strides])
    pretrained=pretrained)
  File "/home/ubuntu/mmdetection/mmdet/models/detectors/two_stage.py", line 44, in __init__
    self.roi_head = build_head(roi_head)
  File "/home/ubuntu/anaconda3/envs/ote-det/lib/python3.7/site-packages/mmcv/utils/registry.py", line 167, in
/home/ubuntu/mmdetection/mmdet/core/bbox/transforms.py:27: TracerWarning: torch.as_tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors 
  if bboxes.size(0) > 0: boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this valueputs!
  File "/home/ubuntu/anaconda3/envs/ote-det/lib/python3.7/site-packages/torch/nn/modules/module.py", line 534
, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/mmdetection/mmdet/models/detectors/base.py", line 127, in forward_test
/home/ubuntu/mmdetection/mmdet/core/bbox/transforms.py:98: TracerWarning: Converting a tensor to a Python boo
        nonzero(Tensor input, *, Tensor out)
Consider using one of the following signatures instead:
        nonzero(Tensor input, *, bool as_tuple)
/home/ubuntu/mmdetection/mmdet/ops/roi_align/roi_align.py:164: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert rois.dim() == 2 and rois.size(1) == 5
/home/ubuntu/mmdetection/mmdet/core/post_processing/bbox_nms.py:55: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if multi_bboxes.shape[1] > 4:
/home/ubuntu/anaconda3/envs/ote-det/lib/python3.7/site-packages/torch/onnx/symbolic_helper.py:243: UserWarning: You are trying to export the model with onnx:Resize for ONNX opset version 10. This operator might cause results to not match the expected results by PyTorch.
ONNX's Upsample/Resize operator did not match Pytorch's Interpolation until opset 11. Attributes to determine how to transform the input were added in onnx:Resize in opset 11 to support Pytorch's behavior (like coordinate_transformation_mode and nearest_mode).
We recommend using opset 11 and above for models using this operator. 
  "" + str(_export_onnx_opset_version) + ". "
/home/ubuntu/anaconda3/envs/ote-det/lib/python3.7/site-packages/torch/onnx/symbolic_opset9.py:1496: UserWarning: ONNX export unsqueeze with negative axis -1 might cause the onnx model to be incorrect. Negative axis is not supported in ONNX. Axis is converted to 1 based on input shape at export time. Passing an tensor of different rank in execution will be incorrect.
  "Passing an tensor of different rank in execution will be incorrect.")
ONNX model has been saved to "./faster_rcnn_x101_64x4d_fpn_1x_coco_player_referee.onnx"
WARNING: ONNX Optimizer has been moved to https://github.com/onnx/optimizer.
All further enhancements and fixes to optimizers will be done in this new repo.
The optimizer code in onnx/onnx repo will be removed in 1.9 release.
```

And what is onnx opset? It says  (from above)

```
UserWarning: You are trying to export the model with onnx:Resize for ONNX opset version 10. This operator might cause results to not match the expected results by PyTorch.
ONNX's Upsample/Resize operator did not match Pytorch's Interpolation until opset 11. Attributes to determine how to transform the input were added in onnx:Resize in opset 11 to support Pytorch's behavior (like coordinate_transformation_mode and nearest_mode).
```

And also:
` /home/ubuntu/anaconda3/envs/ote-det/lib/python3.7/site-packages/torch/onnx/symbolic_opset9.py:1496: UserWarning: ONNX export unsqueeze with negative axis -1 might cause the onnx model to be incorrect. Negative axis is not supported in ONNX. Axis is converted to 1 based on input shape at export time. Passing an tensor of different rank in execution will be incorrect.`

**Comment by druzhkov-paul** [comment]
> And what is onnx opset? It says (from above)

ONNX standard defines a format for AI models. It defines a set of supported operators (or opset for short, [link](https://github.com/onnx/onnx/blob/master/docs/Versioning.md#operator-sets)) and use versioning over them. All operators within one computational graph should have consistent opset versions. PyTorch has its own mechanisms for conversion from PyTorch's native representation of operations to a particular ONNX opset. Some PyTorch and ONNX opsets are not perfectly aligned. The warning message says that there *might* be some inconsistencies between specified PyTorch and ONNX opset versions.

PyTorch exporter for ONNX usually warns the user about some transformations that happen during the process of export. Treating some value as a constant is the most frequent one. And in most situations this is the intended behaviour. I would say that one should take care of these messages while adding export capabilities to a PyTorch project. But once the export is supported and verified those are just logging messages. I'd not worry too much about them.

To make sure that produced ONNX graph is valid, you may [run quality evaluation in ONNXRuntime/OpenVINO](https://github.com/openvinotoolkit/mmdetection/blob/ote/docs/getting_started.md#test-using-openvino-or-onnxruntime) and check if metrics are the same as in PyTorch.

**Comment by devloper13** [comment]
Thanks. What should be given in the --out argument? On giving a folder name it throws:
```
Traceback (most recent call last):
  File "tools/test_exported.py", line 231, in <module>
    sys.exit(main(args) or 0)
  File "tools/test_exported.py", line 201, in main
    mmcv.dump(results, args.out)
  File "/home/ubuntu/anaconda3/envs/ote-det/lib/python3.7/site-packages/mmcv/fileio/io.py", line 74, in dump
    raise TypeError(f'Unsupported format: {file_format}')
TypeError: Unsupported format: conversion_result
```

**Comment by druzhkov-paul** [comment]
python tools/test_exported.py config.py model.onnx --out res.pkl --eval bbox

**Comment by devloper13** [comment]
Thanks!
