### ISSUE TITLE
can tools/export.py be used  in device cpu.

### ISSUE THREAD

**Issue by z-hou** [ovextra/mmdetection#64]
Hi:
   I use export.py to export maskrcnn to onnx format, but always got 
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
device: cpu
get_fake_input.device cpu
Traceback (most recent call last):
  File "tools/export.py", line 299, in <module>
    sys.exit(main(args) or 0)
  File "tools/export.py", line 243, in main
    fake_data = get_fake_input(cfg, device=device)
  File "tools/export.py", line 209, in get_fake_input
    data = scatter(collate([data], samples_per_gpu=1), [device])[0]
  File "/opt/anaconda3/envs/ote-det/lib/python3.7/site-packages/mmcv-0.6.2-py3.7-linux-x86_64.egg/mmcv/parallel/scatter_gather.py", line 40, in scatter
    return scatter_map(inputs)
  File "/opt/anaconda3/envs/ote-det/lib/python3.7/site-packages/mmcv-0.6.2-py3.7-linux-x86_64.egg/mmcv/parallel/scatter_gather.py", line 30, in scatter_map
    out = list(map(type(obj), zip(*map(scatter_map, obj.items()))))
  File "/opt/anaconda3/envs/ote-det/lib/python3.7/site-packages/mmcv-0.6.2-py3.7-linux-x86_64.egg/mmcv/parallel/scatter_gather.py", line 25, in scatter_map
    return list(zip(*map(scatter_map, obj)))
  File "/opt/anaconda3/envs/ote-det/lib/python3.7/site-packages/mmcv-0.6.2-py3.7-linux-x86_64.egg/mmcv/parallel/scatter_gather.py", line 27, in scatter_map
    out = list(map(list, zip(*map(scatter_map, obj))))
  File "/opt/anaconda3/envs/ote-det/lib/python3.7/site-packages/mmcv-0.6.2-py3.7-linux-x86_64.egg/mmcv/parallel/scatter_gather.py", line 18, in scatter_map
    return OrigScatter.apply(target_gpus, None, dim, obj)
  File "/opt/anaconda3/envs/ote-det/lib/python3.7/site-packages/torch/nn/parallel/_functions.py", line 82, in forward
    target_gpus = list(map(lambda x: _get_device_index(x, True), target_gpus))
  File "/opt/anaconda3/envs/ote-det/lib/python3.7/site-packages/torch/nn/parallel/_functions.py", line 82, in <lambda>
    target_gpus = list(map(lambda x: _get_device_index(x, True), target_gpus))
  File "/opt/anaconda3/envs/ote-det/lib/python3.7/site-packages/torch/cuda/_utils.py", line 24, in _get_device_index
    raise ValueError('Expected a cuda device, but got: {}'.format(device))
ValueError: Expected a cuda device, but got: cpu

I wonder if there's a correct version of cuda and pytorch can make export successfully, and whether CPU mode can work in export

**Comment by druzhkov-paul** [comment]
@z-hou You should have compatible CUDA and PyTorch versions to run it. For CPU only export you may try using #65 .

**Comment by z-hou** [comment]
@druzhkov-paul 
Hi, thanks for the answer, it helps a lot.
but I have annother problem, can this tool export the model that trained from  the official repo "/open-mmlab/mmdetection", I just tried, got the error:
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

**Comment by z-hou** [comment]
@druzhkov-paul 
by the way, I can export maskrcnn model succefully which from mode_zoo

**Comment by druzhkov-paul** [comment]
> RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False.

Thanks for catching this. #67 should fix this.

**Comment by z-hou** [comment]
@druzhkov-paul 
Hi, thanks for the reply
when I run test_export.py, got 
OTEdetection/mmdetection$ python tools/test_exported.py configs/mask_rcnn/mask_rcnn_r101_fpn_1x_coco.py onnx/mask_rcnn_r101_fpn_1x_coco.onnx --out onnx --eval bbox segm --show
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
loading annotations into memory...
Done (t=0.32s)
creating index...
index created!
[                                                  ] 0/5000, elapsed: 0s, ETA:Traceback (most recent call last):
  File "tools/test_exported.py", line 215, in <module>
    sys.exit(main(args) or 0)
  File "tools/test_exported.py", line 180, in main
    model.show(display_image, result, score_thr=args.score_thr, wait_time=wait_key)
  File "/media/data2/zhozho/OTEdetection/mmdetection/mmdet/utils/deployment/onnxruntime_backend.py", line 52, in show
    data, result, show=True, score_thr=score_thr, wait_time=wait_time)
  File "/media/data2/zhozho/OTEdetection/mmdetection/mmdet/models/detectors/base.py", line 321, in show_result
    img[mask] = img[mask] * 0.5 + color_mask * 0.5
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

I wonder what's the cause of this problem, thanks very much

**Comment by z-hou** [comment]
@druzhkov-paul 
Hi，I make the change below in tools/test_export.py:
def postprocess(result, img_meta, num_classes=80, rescale=True):
    det_bboxes = result['boxes']
    det_labels = result['labels']
    det_masks = result.get('masks', None)

    if rescale:
        img_h, img_w = img_meta[0]['ori_shape'][:2]
        scale = img_meta[0]['scale_factor']
        det_bboxes[:, :4] /= scale
    else:
        img_h, img_w = img_meta[0]['img_shape'][:2]

    det_bboxes[:, 0:4:2] = np.clip(det_bboxes[:, 0:4:2], 0, img_w - 1)
    det_bboxes[:, 1:4:2] = np.clip(det_bboxes[:, 1:4:2], 0, img_h - 1)

    bbox_results = bbox2result(det_bboxes, det_labels, num_classes)
    if det_masks is not None:
        segm_results = mask2result(
            det_bboxes,
            det_labels,
            det_masks,
            num_classes,
            mask_thr_binary=0.5,
            img_size=(img_h, img_w))
        segm_results = encode_mask_results(segm_results)
        #return bbox_results, segm_results
          return bbox_results
    return bbox_results
and I can get corrcect bbox in result, but if return both bbox and segm, got the error above

**Comment by Ilya-Krylov** [comment]
@z-hou The fix (https://github.com/openvinotoolkit/mmdetection/pull/69) has been merged. Please try it again.
